---
title: "Exoplanet population models"
format: html
bibliography: refs.bib
---

{{< include _macros.qmd >}}

We start with the simplest possible naive model. Then we add back the null model into the mix. 

# Naive prototype

### Model

There are two models that we need notation for. The first one is the octofitter model 
used to fit each system. Let us denote its density by $q$.
The second one is a joint hierarchical model, denote its density by $p$. 

Let $\theta \in \Theta$ denote a pair of separation and mass ratio. We are interested in the 
population distribution of this parameter. 

Let $i$ denote the index of the system, $i \in \{1, 2, \dots, N\}$, 
where $N = 56\,000$ is the number of systems under study, 
and $y_i$ the data for each system.

Let us define some notation for the octofitter model. Let $\phi$ denote nuisance parameters. 
The octofitter prior is $q(\theta, \phi)$. Notice that this prior will be different in 
the hierarchical model, hence the different notation $q$ vs $p$. 
Denote the octofitter likelihood by $L(y | \theta, \phi)$. 
The octofitter posterior is denoted $q(\theta, \phi | y_i)$. We have access to approximate posterior samples
$\left(\theta_{i,j}, \phi_{i,j}\right)$, where $j \in \{1, 2, \dots, M\}$, and
$M = 2^{12}$ is the number of MCMC iterations per system. 

For now let us oversimply and assume each system has a planet, i.e., we do not consider 
the null model yet. This seems surprising since scientifically it is quite important 
to include it, but mathematically this should be easy to add it back, with the 
cost of some messier notation. 

For computational efficiency, assume we have a partition of the parameter space of interest, $\Theta$, into 
$K$ disjoint bins, $\Theta = \Theta_1 \cup \dots \cup \Theta_K$. 
We are interested in population occupancy of these bins. 
To do so, we construct a hierarchical model $p$. 

Let us describe the generative story for simulating from $p$. 

Let $(X_i = k)$ denote the event that the $i$-th system belongs to bin $k$. 
The random variables $X_i$ have a categorical distribution. Let $\eta = (\eta_1, \dots, \eta_K)$ 
denote the parameter of that categorical distribution, $\sum_k \eta_k = 1$. Since we take a 
Bayesian approach, $\eta$ is also a random variable. Importantly, the random variable $\eta$ is shared 
by all systems, allowing us to make population-level inference.
This yields:

\begin{align*}
\eta &\sim \distDir(\alpha) \\
X_i &\sim \distCat(\eta). 
\end{align*}

Now once we have picked a block $\Theta_x$ in the partition, we assume that we pick 
a specific parameter *proportionally to the octofitter prior restricted to $\Theta_x$*. 
Finally, the data is generated using the octofitter likelihood:

\begin{align*}
\theta_i, \phi_i | X_i = x &\sim q(\theta, \phi) \ind[\theta \in \Theta_x] \\
y_i | \theta_i, \phi_i &\sim L(y | \theta, \phi). 
\end{align*}

With these choices, notice that once we know the bin identity, the generative 
story for $p$ and $q$ match up. This will allow us to bridge the two models via the identiy $q(y | x) = p(y | x)$. 


### Computation

We now turn to the question of approximating the posterior of $p$ based on 
the $56\,000$ approximate posteriors for $q$. 

As a preprocessing step, we first approximate the binned posteriors $q(x_i | y_i)$:
$$q_{x, i} = \frac{1}{M} \sum_{j=1}^{M} \ind[\theta_{i,j} \in \Theta_x].$$

We will also need to approximate octofitter priors, binned using the same partition, $q(x)$:
$$q_x = \frac{1}{M} \sum_{j=1}^{M} \ind[\theta_{j} \in \Theta_x],$$
where $\theta_j$ are samples from the octofitter prior, $q(\theta)$. 

We now show how to evaluate the un-normalized density of the population model:
$$p(\eta | y_1, \dots, y_N) \propto p(\eta) \prod_{i=1}^N p(y_i | \eta). $$
Each of the likelihood factor is computed as follows:
\begin{align*}
p(y_i | \eta) &= \sum_{x_i = 1}^K p(y_i, x_i|\eta) \\
&= \sum_{x_i=1}^K p(x_i | \eta) p(y_i | x_i, \eta).
\end{align*}

By definition, $p(x_i | \eta) = \eta_x$. For the second term, note first that 
by construction, $\eta$ is conditionally independent of $y_i$ given $x_i$, i.e., 
$p(y_i | x_i, \eta) = p(y_i | x_i)$, Next, we use 
the identity $p(y_i | x_i) = q(y_i | x_i)$ mentioned earlier. Then from Bayes rule, 
$q(y_i | x_i) = q(y_i) q(x_i | y_i) / q(x_i) \propto q(x_i | y_i) / q(x_i)$ which 
we can approximate with $q_{x,i} / q_x$. 
Putting it all together:
\begin{align*}
p(y_i | \eta) &\approx \sum_{x=1}^K \frac{\eta_x q_{x,i}}{q_x}.
\end{align*}


# Adding a null model

### Model

We now consider the possibility that some systems may not have planets. This 
introduces a new model, the null model $n$. 

Let $\psi$ denote parameters for the null models, and $N_i$ the marginal 
likelihood under the null model for system $i$:
$$N_i = n(y_i) = \int q(\psi) L_0(y_i | \psi).$$

In contrast to the last section, we will also need marginal likelihood estimates 
under the octofitter model with one planet, denoted:
$$Z_i = q(y_i) = \int \int q(\theta, \phi) L(y_i | \theta, \phi).$$

The marginal likelihood estimates $N_i$ and $Z_i$ are part of the Pigeons output. 

Next, we move to modifying the population model $p$ to incorporate the possibility 
that there are no planets in a given system. 

We modify the random variable $X_i$: if it takes the value zero, we interpret 
$(X_i = 0)$ as the event that there are no planet, otherwise, $(X_i = x)$ for 
$x > 0$ is the same bin membership indicator as in the last section. 

We introduce a new random variable, $\pi$, which is the proportion of systems with at 
least one planet. Again this is a random variable shared among all the systems. 
Once it has been decided that there is a planet, then its bin is selected as 
before, i.e., according to a categorical with parameter $\eta$. 

We place a beta prior on $\pi$:
$$\pi \sim \distBeta(\alpha, \beta).$$
We keep the same prior on $\eta$, and modify the categorical distribution on $x$ as follows:
$$X_i | \pi, \eta \sim \distCat_{\{0, 1, \dots, K\}}(1-\pi, \pi \eta_1, \pi \eta_2, \dots, \pi \eta_K).$$
Finally, the likelihood for $y_i$ is the same as in the last section for $x_i > 0$, 
and is given by the null model if $x_i = 0$. 


### Computation

We now approximate the density under the population model equipped with the null model:
$$p(\eta, \pi | y_1, \dots, y_N) \propto p(\eta) p(\pi) \prod_{i=1}^N p(y_i | \eta, \pi). $$

We now look at each factor in the product and proceed similarly to what we did in 
the prototype model studied in the first section:
\begin{align*}
p(y_i | \eta, \pi) &= \sum_{x_i = 0}^K p(y_i, x_i|\eta, \pi) \\
&= \sum_{x_i=0}^K p(x_i | \eta, \pi) p(y_i | x_i, \eta, \pi).
\end{align*}
There are two cases to consider in that sum: either $x_i = 0$ (no planet) or $x_i > 0$ (planet present).

We start with the term with $x_i = 0$. In that case, $p(x_i | \eta, \pi) = 1 - \pi$, 
and $p(y_i | x_i, \eta, \pi) = p(y_i | x_i) = N_i$. 

Next, suppose $x_i > 0$. Then $p(x_i | \eta, \pi) = \pi \eta_{x_i}$, and 
as before,
$q(y_i | x_i) = q(y_i) q(x_i | y_i) / q(x_i)$, but this time we cannot ignore 
the normalization $q(y_i) = Z_i$ because the previous term ($x_i = 0$) does not contain 
that factor. 

Putting this together:
$$p(y_i | \eta, \pi) \approx (1-\pi) N_i + \sum_{x=1}^K \frac{\pi \eta_x Z_i q_{x, i}}{q_i}.$$


# Alternative: independence MH

The above approach assumes a specific form for the population model, based on a finite discretization of 
the parameter space of interest $\Theta$. 
We now consider an alternative inference approach based on independence MH which gives more flexibility on the population model. 
The cost per iteration is also lower compared to approach from the previous section, 
but the mixing time complicates comprehensive efficiency analysis. 


### Model

Recall we are interested in an unknown population density $\mu$ defined on the space $\Theta$. 
In the above, we assumed a piecewise constant $\mu$ defined on a grid. But other alternatives might 
be interesting to consider, for example parametric families (including mixtures). 
Taking a Bayesian approach, we take $\mu$ to be a random variable. Let $\text{PriorOnPopulation}$ 
denote the prior on $\mu$. 

In the generative story,
once we have sampled $\mu$, planet parameters are sampled from $\mu$, i.e.,
$\theta_i | \mu \sim \mu$.

Let $z_i$ denote the indicator that system $i$ has at least one planet ($z_i = 1$ if so, $z_i = 0$ otherwise).

The rest of the model follows the same structure as before:
\begin{align*}
\mu &\sim \text{PriorOnPopulation} \\
\pi &\sim \distBeta(\alpha, \beta) \\
\theta_i | \mu &\sim \mu \\
\phi_i | \theta_i &\sim q(\phi_i | \theta_i) \\
\psi_i &\sim q(\phi_i) \\
z_i | \pi &\sim \distBern(\pi).
\end{align*}
Finally, if $z_i = 1$, $y_i | \theta_i, \phi_i \sim L(y_i | \theta_i, \phi_i)$, else, $y_i | \psi_i \sim L_0(y_i | \psi_i)$. 


### Computation

We describe an MCMC algorithm for the population model, which is based on block updates. 
Note that there are two different types of MCMC at play: those from the previous run 
on each individual system, and one for the populatio model. To disambiguate, we will 
use a bar superscript on the population run, $\bar \mu_j, \bar \pi_j, \bar \theta_{i,j}$, etc, 
where $j \in \{1, 2, \dots, \bar M\}$. For simplicity, assume $M = \bar M$, i.e., all 
MCMC proceed for the same number of iterations. 

The updates $\bar \mu_j | \text{rest}$ and $\bar \pi_j | \text{rest}$ are low dimensional, so they 
should not be bottlenecks. 

Similarly, the updates for $\bar z_{i,j} | \text{rest}$ consist in normalizing two numbers computed 
from cached likelihood values, so they should also be fast. 

The more challenging updates are for $\bar \theta_{i,j}, \bar \phi_{i,j}, \bar \psi_{i,j}$. 
To speed-up inference we will use the traces from the system specific runs, $\left(\theta_{i,j}, \phi_{i,j}\right)$, to 
build a smart independence proposal. Since the proposal will only differ in a low dimensional prior factor
(and not in the likelihood), we expect the acceptance to be bounded away from zero. 

Recall that for each $i$, the trace $\left(\theta_{i,j}, \phi_{i,j}\right)$ is approximately 
distributed according to $\rho_i(\theta, \phi) \propto q(\theta) q(\phi | \theta) L(y_i | \theta, \phi)$. 
Similarly, we have access to traces approximately distributed according to $\tau_i(\psi) \propto q(\psi) L_0(y_i | \psi)$.
In the following algorithm, sampling from $\rho_i$ and $\tau_i$ will be 
approximated by popping one sample from the system specific traces. 

Now we proceed as follows to sample from $\bar \theta_i, \bar \phi_i, \bar \psi_i$. 
At iteration $j$ of the MCMC algorithm targeting the population model, loop over 
the systems $i$, and for each $i$:

1. If $\bar x_{i,j} = 1$ 
    a. Propose $\theta', \phi' \sim \rho_i$ (via a system trace pop).
    b. Accept with probability $\min\{1, r(\theta') / r(\bar \theta_{i,j-1})\}$, where $r(\theta) = \bar \mu_j(\theta) / q(\theta)$. 
2. Otherwise 
    a. Propose $\psi' \sim \tau_i$ (via a system trace null model pop). 
    b. Always accept. 

The reason for the simple acceptance ratio is that the system specific MCMC differ 
from the population level MCMC by only the prior on $\theta_{i}$, allowing cancellation of the other factors.


### Annealing 

Interestingly, standard annealing does not appear to be suitable because of this 
specialized sampler which only achieves these simplified acceptance probabilities when the 
likelihood exactly matches the system-specific likelihoods. 

As an alternative to standard annealing, consider the following continuum of distributions 
$\pi_\beta$ obtained by changing one line in the generative process:
$$\theta_i | \mu \sim \beta \mu + (1-\beta) q.$$
Notice that we recover the posterior at $\beta = 1$, and that at $\beta = 0$, the 
independence MH algorithm always accept both types of moves. 


# Relation between the spike-and-slab and stepping stone approaches

Originally, the quantities $N_i$ and $Z_i$ were computed separately using two octofitter runs based on Pigeons for 
each system and using the stepping stone estimator reported by Pigeons. 
Inspection of the math in the previous sections reveals that only the ratios $Z_i / N_i$ are 
needed (this can be seen by dividing all equation by $\prod_i N_i$, a constant with respect 
to all parameters of interest). 
From this observation, it can be seen that as an alternative to the stepping-stone, one 
can instead use a spike-and-slab model where we introduce a uniform binary random variable $B_i \sim \distBern(1/2)$ 
(note we use small cap here) indicating the presence or absence of planet. 
Then we use *model saturation* (Carlin and Chibs, 1995) to create one new octofitter model per star
having the property that $p(b_i = 1 | y_i) = Z_i / (Z_i + N_i)$. 


# The semi-hierarchical model 

The hierarchical model described so far is "full" in the sense that the different stars share both $\eta$ and $\pi$ 
at the population level. 
An alternative is to share only $\pi$. This yields the following model:

\begin{align*}
\pi &\sim \distBeta(\alpha, \beta) \\
\theta_i, \phi_i &\sim q(\cdot, \cdot) \\
\psi_i &\sim q(\cdot) \\
b_i | \pi &\sim \distBern(\pi), \\
\end{align*}
and, finally, if $b_i = 1$, $y_i | \theta_i, \phi_i \sim L(y_i | \theta_i, \phi_i)$, else, $y_i | \psi_i \sim L_0(y_i | \psi_i)$. 

We now turn to the problem of computing the posterior of the semi-hierarchical model from individual spike-and-slab models. 
The calculations are a special case of the material covered in the section on "adding a null model" by picking $K = 1$. 
In that case, since there is a single bin, note that $q_{x,i} = q_i = \eta_x = 1$. 
This yields (after division by $\prod_i N_i$):
$$p(\pi | y_1, \dots, y_N) \propto p(\pi) \prod_{i=1}^N \left( (1 - \pi) + \pi \frac{Z_i}{N_i}  \right),$$
where $p(\pi)$ is the prior on the shared planet prevalence parameter $\pi$. 

The advantage of this approach is that using the machinery from the previous sections, all latent variables except $\pi$ 
can be marginalized. This means that the posterior can be computed up to numerical precision using numerical integration.




# References

::: {#refs}
:::


